### ISSUE TITLE
Redmine: Customizing Fonts in Exported PDF

### ISSUE THREAD

**Issue by skhutat** [naitoh/rbpdf#55]
Hi,

Im using redmine and really need to customize the PDF export functionality thats done through rbpdf. However,  I cant figure out how to customize the font when exporting Issues with Arabic (RTL) language content and text. 

Can someone guide me to where the customizations need to be applied?

Thanks
Salim

**Comment by mohd-bs82** [comment]
same problem

**Comment by ashrafalzyoud** [comment]
@vividtone

**Comment by ashrafalzyoud** [comment]
Processing by IssuesController#index as PDF
  Parameters: {"set_filter"=>"1", "tracker_id"=>"1", "project_id"=>"a"}
  Current user: admin (id=1)
  Rendering issues/index.pdf.erb
  Rendered issues/index.pdf.erb (27.6ms)
Completed 500 Internal Server Error in 107ms (ActiveRecord: 19.4ms)
  
ActionView::Template::Error (can't modify frozen String):
    1: <%= raw issues_to_pdf(@issues, @project, @query) %>
  
lib/redmine/export/pdf.rb:58:in `delete!'
lib/redmine/export/pdf.rb:58:in `SetFont'
lib/redmine/export/pdf.rb:51:in `SetFontStyle'
lib/redmine/export/pdf/issues_pdf_helper.rb:403:in `calc_col_width'
lib/redmine/export/pdf/issues_pdf_helper.rb:278:in `issues_to_pdf'
app/views/issues/index.pdf.erb:1:in `_app_views_issues_index_pdf_erb___2561031185156740809_46938098228560'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by ahorek** [comment]
@ashrafalzyoud thanks for the report! it's a bug https://www.redmine.org/issues/32832 should fix it

**Comment by ashrafalzyoud** [comment]
big thx brother @ahorek

**Comment by vividtone** [comment]
As @ahorek wrote, this is not a bug of rbpdf but Redmine 4.1.0. The fix has just been committed.

**Comment by ashrafalzyoud** [comment]
@vividtone  brother because i dont have account in redmine.org
can u help me about my issue
i need option to custom field unique not duplicated data
like if user 1, enter cfs[5]=100 if any other user enter the same cfs[5]=100 give him error msg duplicated value

**Comment by ahamdan1990** [comment]
Dears,
Can i render "data:image/png;base64,....." as an image using rbpdf library.
thanks

**Comment by ashrafalzyoud** [comment]
in  redmine 6.0.5
the letter arabic (ق) its appearing squar 
if im change font DejaVuSans in accrobat reader its working
@vividtone  this problem happend in redmine 6.0.5

![Image](https://github.com/user-attachments/assets/df66e07f-5a8c-449d-8dc7-3bd26b6543e6)
